### ISSUE TITLE
Top half clipped

### ISSUE THREAD

**Issue by aoponcedeleon** [ospfranco/sol#46]
Hi Oscar,

I just downloaded the newest version because I wanted to try out the transparency. Had 1.1.32 before this and it worked fine. Now it seems that the top half of the search is clipped out when I press `cmd + k`

### Screenshots

<img width="798" alt="Screen Shot 2022-07-29 at 2 20 02 PM" src="https://user-images.githubusercontent.com/28593720/181695798-090d529f-e0ba-4a6b-99ca-f84ae4a9f6c6.png">

<img width="761" alt="Screen Shot 2022-07-29 at 2 24 53 PM" src="https://user-images.githubusercontent.com/28593720/181696408-b8011783-65c3-402d-a3fd-6291ea585c54.png">

Love the app Oscar!

**Comment by ospfranco** [comment]
cmd + k?

Can you give a bit more details, which macOS version are you using for example? on monterrey it is working fine for me

**Comment by aoponcedeleon** [comment]
Oh my bad, I meant to say `cmd + space`

I'm using Monterey as well (Ver 12.4)

**Comment by ospfranco** [comment]
Weird, have you tried restarting the app? Otherwise I will try to take a look over the weekend

**Comment by aoponcedeleon** [comment]
Yeah, I even tried reinstalling it, but to no avail.

Alright, will keep testing it. Thanks!

**Comment by ospfranco** [comment]
Would be nice if you can provide more details, screen resolution? multiple monitors? etc

**Comment by aoponcedeleon** [comment]
**OS:**
MacOS Monterey 12.4

**Chip:** 
Apple M1 Pro

**Screen Res:**
3024 x 1984 
Display Settings is set to Default (it says Looks like 1512 x 982 when looking at the scaled resolution) 

Issue occurs both when connected to a second monitor and when not connected. I've also tried restarting the app after connecting it to the monitor and it still happens. 

The resolution of the second monitor I plug into is 1920 x 1080.

**Comment by ospfranco** [comment]
I just tried re-installing 1.1.33 from the releases page and everything is working for me. Any additional info you could give?

**Comment by ospfranco** [comment]
I've released a new version 1.1.34 with a minor native change, maybe it will fix it

**Comment by aoponcedeleon** [comment]
I've updated my Mac to the Monterey 12.5, using your newest version , and it doesn't do that anymore!

Pretty unclear what caused it to malfunction in the first place but I think it's all good now, thanks! :)

**Comment by ospfranco** [comment]
ah, then it was the macOS version... every release is a bag of bugs nowadays :P anyways, glad to see it is fixed!

**Comment by etherealSunshine** [comment]
Hi, I'm still having this issue
OS:
macOS Monterey 12.5

Chip:
Apple M1 

Screen Res:
2560 × 1600

Any Suggestions on how to fix this? I tried reinstalling through brew and manually installing 1.1.34
Thanks!

**Comment by etherealSunshine** [comment]
this is how it shows up for me for reference 
<img width="794" alt="image" src="https://user-images.githubusercontent.com/81072340/183850859-9f73038e-050c-479f-874e-017781475ec5.png">

**Comment by ospfranco** [comment]
I just released a new version (1.1.36) can you try that one?

**Comment by ospfranco** [comment]
You won't be able to fix this with any settings, it's a problem with RN macOS and the UI view constraints, unfortunately I'm not able to reproduce the issue on my machines so I'm blindly trying stuff to see what fixes it

**Comment by NickTaylor-** [comment]
1.1.36 still has this issue on my machine (M1 on 12.5).

It looks like the offset _may_ be worse, but its hard to tell.
<img width="862" alt="image" src="https://user-images.githubusercontent.com/6677407/183903889-1b711f91-1d7d-4ca4-abe0-faa429523bd8.png">

**Comment by ospfranco** [comment]
If any UIKit expert is out there:

https://github.com/ospfranco/sol/blob/main/macos/sol-macOS/AppDelegate.swift#L67

Any help getting auto constraints to work properly would be appreciated... I'll give a day or so, otherwise revert it to a full size window until I can get it to work properly

**Comment by ospfranco** [comment]
I've released version 1.1.37, I've removed the blurry window effect (which was causing the window not being properly placed) let me know if you have issues still

**Comment by etherealSunshine** [comment]
still shows up like this
<img width="775" alt="image" src="https://user-images.githubusercontent.com/81072340/184086688-59a0272d-7b6f-4cf1-938d-d9952ba296d6.png">

**Comment by mgussekloo** [comment]
Yup, same here

**Comment by ospfranco** [comment]
There is a new 1.1.40 with yet another try to fix the issue, let me know if it works

**Comment by NickTaylor-** [comment]
That seems to have fixed it 🎉

Thank you so much ❤️

**Comment by etherealSunshine** [comment]
Yep same here!
